USE JULY_2

CREATE TABLE DAT3
(
D3_ID INT PRIMARY KEY ,
D3_FNAME VARCHAR(23),
D3_AGE INT
);
SELECT * TABLE DAT3;
SELECT * FROM DAT3 where D3_AGE=(SELECT W5_ENR FROM WE5 WHERE W5_ENR=23);
SELECT * FROM DAT3 WHERE D3_AGE> ( SELECT AVG(D3_AGE) FROM DAT3);
SELECT AVG(D3_AVG) FROM DAT3